parking_spaces:

# -------- FØRSTE RÆKKE --------
  P1:
    polygon: [[ 15, 120 ], [ 115, 120 ], [ 115, 300 ], [ 15, 300 ]] # TL, TR, BR, BL
    debug_label: "P1"
  P2:
    polygon: [[ 115, 120 ], [ 222, 120 ], [ 222, 300 ], [ 115, 300 ]]
    debug_label: "P2"
  P3:
    polygon: [[ 222, 120 ], [ 333, 120 ], [ 333, 300 ], [ 222, 300 ]]
    debug_label: "P3"
  P4:
    polygon: [[ 333, 120 ], [ 440, 120 ], [ 440, 300 ], [ 333, 300 ]]
    debug_label: "P4"
  P5:
    polygon: [[ 440, 120 ], [ 542, 120 ], [ 542, 300 ], [ 440, 300 ]]
    debug_label: "P5"
  P6:
    polygon: [[ 542, 120 ], [ 640, 120 ], [ 640, 300 ], [ 542, 300 ]]
    debug_label: "P6"
  P7:
    polygon: [[ 640, 120 ], [ 720, 120 ], [ 720, 300 ], [ 640, 300 ]]
    debug_label: "P7"

# -------- ANDEN RÆKKE --------

  P8:
    polygon: [ [ 15, 300 ], [ 115, 300 ], [ 115, 480 ], [ 15, 480 ] ]
    debug_label: "P8"
  P9:
    polygon: [ [ 115, 300 ], [ 222, 300 ], [ 222, 480 ], [ 115, 480 ] ]
    debug_label: "P9"
  P10:
    polygon: [ [ 222, 300 ], [ 333, 300 ], [ 333, 480 ], [ 222, 480 ] ]
    debug_label: "P10"
  P11:
    polygon: [ [ 333, 300 ], [ 440, 300 ], [ 440, 480 ], [ 333, 480 ] ]
    debug_label: "P11"
  P12:
    polygon: [ [ 440, 300 ], [ 542, 300 ], [ 542, 480 ], [ 440, 480 ] ]
    debug_label: "P12"
  P13:
    polygon: [ [ 542, 300 ], [ 640, 300 ], [ 640, 480 ], [ 542, 480 ] ]
    debug_label: "P13"
  P14:
    polygon: [ [ 640, 300 ], [ 720, 300 ], [ 720, 480 ], [ 640, 480 ] ]
    debug_label: "P14"

# -------- TREDJE RÆKKE (Y=630 til Y=815) --------

  P15:
    polygon: [[ 15, 630 ], [ 115, 630 ], [ 115, 815 ], [ 15, 815 ]]
    debug_label: "P15"
  P16:
    polygon: [[ 115, 630 ], [ 222, 630 ], [ 222, 815 ], [ 115, 815 ]]
    debug_label: "P16"
  P17:
    polygon: [[ 222, 630 ], [ 333, 630 ], [ 333, 815 ], [ 222, 815 ]]
    debug_label: "P17"
  P18:
    polygon: [[ 333, 630 ], [ 440, 630 ], [ 440, 815 ], [ 333, 815 ]]
    debug_label: "P18"
  P19:
    polygon: [[ 440, 630 ], [ 542, 630 ], [ 542, 815 ], [ 440, 815 ]]
    debug_label: "P19"
  P20:
    polygon: [[ 542, 630 ], [ 640, 630 ], [ 640, 815 ], [ 542, 815 ]]
    debug_label: "P20"
  P21:
    polygon: [[ 640, 630 ], [ 720, 630 ], [ 720, 815 ], [ 640, 815 ]]
    debug_label: "P21"


# -------- SIDSTE RÆKKE (Y=815 til Y=1005) --------

  P22:
    polygon: [[ 15, 815 ], [ 115, 815 ], [ 115, 1005 ], [ 15, 1005 ]]
    debug_label: "P22"
  P23:
    polygon: [[ 115, 815 ], [ 222, 815 ], [ 222, 1005 ], [ 115, 1005 ]]
    debug_label: "P23"
  P24:
    polygon: [[ 222, 815 ], [ 333, 815 ], [ 333, 1005 ], [ 222, 1005 ]]
    debug_label: "P24"
  P25:
    polygon: [[ 333, 815 ], [ 440, 815 ], [ 440, 1005 ], [ 333, 1005 ]]
    debug_label: "P25"
  P26:
    polygon: [[ 440, 815 ], [ 542, 815 ], [ 542, 1005 ], [ 440, 1005 ]]
    debug_label: "P26"
  P27:
    polygon: [[ 542, 815 ], [ 640, 815 ], [ 640, 1005 ], [ 542, 1005 ]]
    debug_label: "P27"
  P28:
    polygon: [[ 640, 815 ], [ 720, 815 ], [ 720, 1005 ], [ 640, 1005 ]]
    debug_label: "P28"